version: '2'
services:
    pantryapp-app:
        image: pantryapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pantryapp-postgresql:5432/pantryApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pantryapp-postgresql:
        extends:
            file: postgresql.yml
            service: pantryapp-postgresql
